include: ../../analysis_options.yaml

linter:
  rules:
    # TODO(goderbauer): enable when super params are more established and
    #   seeing them in the API samples is no longer surprising,
    #   https://github.com/flutter/flutter/issues/101068
    use_super_parameters: false
